"""add_execution_models

Revision ID: 772f33b1bdc9
Revises: 775a6749df00
Create Date: 2026-07-31 22:59:15.251062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '772f33b1bdc9'
down_revision: Union[str, None] = '775a6749df00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_executions',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_executions_campaign_id'), 'campaign_executions', ['campaign_id'], unique=False)
    op.create_table('execution_states',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('current_lead_id', sa.String(length=36), nullable=True),
    sa.Column('current_worker_id', sa.String(length=36), nullable=True),
    sa.Column('current_session', sa.String(length=255), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('remaining_leads', sa.Integer(), nullable=False),
    sa.Column('processed_leads', sa.Integer(), nullable=False),
    sa.Column('failed_leads', sa.Integer(), nullable=False),
    sa.Column('skipped_leads', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('last_checkpoint', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_states_campaign_id'), 'execution_states', ['campaign_id'], unique=True)
    op.create_table('execution_workers',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('worker_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_queue_id', sa.String(length=36), nullable=True),
    sa.Column('last_ping', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_workers_campaign_id'), 'execution_workers', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_workers_campaign_id'), table_name='execution_workers')
    op.drop_table('execution_workers')
    op.drop_index(op.f('ix_execution_states_campaign_id'), table_name='execution_states')
    op.drop_table('execution_states')
    op.drop_index(op.f('ix_campaign_executions_campaign_id'), table_name='campaign_executions')
    op.drop_table('campaign_executions')
    # ### end Alembic commands ###
