"""add_contact_history_table

Revision ID: 775a6749df00
Revises: adb31b6cdfcc
Create Date: 2026-07-31 22:23:45.670837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775a6749df00'
down_revision: Union[str, None] = 'adb31b6cdfcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_history',
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('instagram_username', sa.String(length=255), nullable=False),
    sa.Column('instagram_account', sa.String(length=255), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_status', sa.String(length=50), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('first_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_delivery_status', sa.String(length=50), nullable=True),
    sa.Column('last_failure_reason', sa.String(), nullable=True),
    sa.Column('last_execution_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['message_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instagram_username', 'instagram_account', name='uq_contact_history_user_account')
    )
    op.create_index('ix_contact_history_account', 'contact_history', ['instagram_account'], unique=False)
    op.create_index(op.f('ix_contact_history_campaign_id'), 'contact_history', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_contact_history_lead_id'), 'contact_history', ['lead_id'], unique=False)
    op.create_index(op.f('ix_contact_history_template_id'), 'contact_history', ['template_id'], unique=False)
    op.create_index('ix_contact_history_username', 'contact_history', ['instagram_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_history_username', table_name='contact_history')
    op.drop_index(op.f('ix_contact_history_template_id'), table_name='contact_history')
    op.drop_index(op.f('ix_contact_history_lead_id'), table_name='contact_history')
    op.drop_index(op.f('ix_contact_history_campaign_id'), table_name='contact_history')
    op.drop_index('ix_contact_history_account', table_name='contact_history')
    op.drop_table('contact_history')
    # ### end Alembic commands ###
