"""add_automation_safety_layer_settings

Revision ID: ace269def537
Revises: 6ffa8222f012
Create Date: 2026-07-31 19:24:21.172375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace269def537'
down_revision: Union[str, None] = '6ffa8222f012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('automation_min_delay_ms', sa.Integer(), server_default='2000', nullable=False))
    op.add_column('settings', sa.Column('automation_max_delay_ms', sa.Integer(), server_default='5000', nullable=False))
    op.add_column('settings', sa.Column('automation_nav_timeout_ms', sa.Integer(), server_default='30000', nullable=False))
    op.add_column('settings', sa.Column('automation_max_profiles_per_run', sa.Integer(), server_default='100', nullable=False))
    op.add_column('settings', sa.Column('automation_max_runtime_sec', sa.Integer(), server_default='3600', nullable=False))
    op.add_column('settings', sa.Column('automation_pause_duration_sec', sa.Integer(), server_default='300', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'automation_pause_duration_sec')
    op.drop_column('settings', 'automation_max_runtime_sec')
    op.drop_column('settings', 'automation_max_profiles_per_run')
    op.drop_column('settings', 'automation_nav_timeout_ms')
    op.drop_column('settings', 'automation_max_delay_ms')
    op.drop_column('settings', 'automation_min_delay_ms')
    # ### end Alembic commands ###
