"""ai_discovery_production_hardening

Revision ID: adb31b6cdfcc
Revises: ebb3eb7a07a1
Create Date: 2026-07-31 21:24:59.640535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adb31b6cdfcc'
down_revision: Union[str, None] = 'ebb3eb7a07a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_discovery', sa.Column('normalized_prompt', sa.Text(), server_default="", nullable=False))
    op.add_column('ai_discovery', sa.Column('prompt_version', sa.String(length=50), server_default="v1", nullable=False))
    op.add_column('ai_discovery', sa.Column('api_key_index', sa.Integer(), nullable=True))
    op.add_column('ai_discovery', sa.Column('prompt_tokens', sa.Integer(), server_default="0", nullable=False))
    op.add_column('ai_discovery', sa.Column('completion_tokens', sa.Integer(), server_default="0", nullable=False))
    op.add_column('ai_discovery', sa.Column('total_tokens', sa.Integer(), server_default="0", nullable=False))
    op.add_column('ai_discovery', sa.Column('cached', sa.Boolean(), server_default="0", nullable=False))
    op.add_column('ai_discovery', sa.Column('retry_count', sa.Integer(), server_default="0", nullable=False))
    with op.batch_alter_table('ai_discovery') as batch_op:
        batch_op.drop_column('tokens_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_discovery', sa.Column('tokens_used', sa.INTEGER(), nullable=False))
    with op.batch_alter_table('ai_discovery') as batch_op:
        batch_op.drop_column('retry_count')
        batch_op.drop_column('cached')
        batch_op.drop_column('total_tokens')
        batch_op.drop_column('completion_tokens')
        batch_op.drop_column('prompt_tokens')
        batch_op.drop_column('api_key_index')
        batch_op.drop_column('prompt_version')
        batch_op.drop_column('normalized_prompt')
    # ### end Alembic commands ###
