"""add_ai_discovery

Revision ID: ebb3eb7a07a1
Revises: ace269def537
Create Date: 2026-07-31 21:03:02.636609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ebb3eb7a07a1'
down_revision: Union[str, None] = 'ace269def537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_discovery',
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('original_prompt', sa.Text(), nullable=False),
    sa.Column('parsed_filters', sa.JSON(), nullable=False),
    sa.Column('groq_model', sa.String(length=100), nullable=True),
    sa.Column('api_key_used', sa.String(length=255), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_discovery_campaign_id'), 'ai_discovery', ['campaign_id'], unique=False)
    # op.drop_index('ix_business_intelligence_lead_id', table_name='business_intelligence')
    # op.drop_index('ix_business_intelligence_normalized_url', table_name='business_intelligence')
    # op.drop_table('business_intelligence')
    with op.batch_alter_table('leads') as batch_op:
        batch_op.alter_column('website',
                   existing_type=sa.VARCHAR(length=1024),
                   type_=sa.String(length=255),
                   existing_nullable=True)
    op.add_column('website_analyses', sa.Column('ai_score', sa.Integer(), nullable=True))
    op.add_column('website_analyses', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('website_analyses', sa.Column('strengths', sa.String(), nullable=True))
    op.add_column('website_analyses', sa.Column('weaknesses', sa.String(), nullable=True))
    op.add_column('website_analyses', sa.Column('recommendation', sa.String(), nullable=True))
    op.add_column('website_analyses', sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('website_analyses', sa.Column('prompt_version', sa.String(length=50), nullable=True))
    op.add_column('website_analyses', sa.Column('model_used', sa.String(length=50), nullable=True))
    op.add_column('website_analyses', sa.Column('id', sa.String(length=36), nullable=False))
    op.add_column('website_analyses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.add_column('website_analyses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    with op.batch_alter_table('website_analyses') as batch_op:
        batch_op.alter_column('website',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=False)
    op.create_index(op.f('ix_website_analyses_website'), 'website_analyses', ['website'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_analyses_website'), table_name='website_analyses')
    op.alter_column('website_analyses', 'website',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('website_analyses', 'updated_at')
    op.drop_column('website_analyses', 'created_at')
    op.drop_column('website_analyses', 'id')
    op.drop_column('website_analyses', 'model_used')
    op.drop_column('website_analyses', 'prompt_version')
    op.drop_column('website_analyses', 'analyzed_at')
    op.drop_column('website_analyses', 'recommendation')
    op.drop_column('website_analyses', 'weaknesses')
    op.drop_column('website_analyses', 'strengths')
    op.drop_column('website_analyses', 'summary')
    op.drop_column('website_analyses', 'ai_score')
    op.alter_column('leads', 'website',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.create_table('business_intelligence',
    sa.Column('lead_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('website', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('normalized_url', sa.VARCHAR(length=1024), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('crawl_date', sa.DATETIME(), nullable=True),
    sa.Column('pages_crawled', sa.INTEGER(), nullable=False),
    sa.Column('business_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('industry', sa.VARCHAR(length=255), nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone_numbers', sqlite.JSON(), nullable=False),
    sa.Column('emails', sqlite.JSON(), nullable=False),
    sa.Column('addresses', sqlite.JSON(), nullable=False),
    sa.Column('social_links', sqlite.JSON(), nullable=False),
    sa.Column('navigation', sqlite.JSON(), nullable=False),
    sa.Column('hero_content', sqlite.JSON(), nullable=False),
    sa.Column('about_content', sa.TEXT(), nullable=True),
    sa.Column('services', sqlite.JSON(), nullable=False),
    sa.Column('testimonials', sqlite.JSON(), nullable=False),
    sa.Column('faq', sqlite.JSON(), nullable=False),
    sa.Column('contact_information', sqlite.JSON(), nullable=False),
    sa.Column('cta_buttons', sqlite.JSON(), nullable=False),
    sa.Column('logo_path', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('brand_colors', sqlite.JSON(), nullable=False),
    sa.Column('fonts', sqlite.JSON(), nullable=False),
    sa.Column('images', sqlite.JSON(), nullable=False),
    sa.Column('favicon', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('technology_stack', sqlite.JSON(), nullable=False),
    sa.Column('cms', sa.VARCHAR(length=100), nullable=True),
    sa.Column('framework', sa.VARCHAR(length=100), nullable=True),
    sa.Column('meta_title', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('meta_description', sa.TEXT(), nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), nullable=True),
    sa.Column('internal_links', sa.INTEGER(), nullable=False),
    sa.Column('external_links', sa.INTEGER(), nullable=False),
    sa.Column('performance_summary', sqlite.JSON(), nullable=False),
    sa.Column('mobile_friendly', sa.BOOLEAN(), nullable=False),
    sa.Column('ssl_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('homepage_screenshot', sa.VARCHAR(length=1024), nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_business_intelligence_normalized_url', 'business_intelligence', ['normalized_url'], unique=False)
    op.create_index('ix_business_intelligence_lead_id', 'business_intelligence', ['lead_id'], unique=1)
    op.drop_index(op.f('ix_ai_discovery_campaign_id'), table_name='ai_discovery')
    op.drop_table('ai_discovery')
    # ### end Alembic commands ###
